Q.1 For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), Find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [2]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
sum_all = np.sum(gfg)
print("Sum of all elements:", sum_all)

# ii. Sum of all elements row-wise
sum_row_wise = np.sum(gfg, axis=1)
print("Sum of elements row-wise:", sum_row_wise)

# iii. Sum of all elements column-wise
sum_col_wise = np.sum(gfg, axis=0)
print("Sum of elements column-wise:", sum_col_wise)


Sum of all elements: 45
Sum of elements row-wise: [[14]
 [16]
 [15]]
Sum of elements column-wise: [[20  9 16]]


Q.2 (a)For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements
(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only

In [3]:
import numpy as np

# Part (a)
array_a = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array_a)
indices_sorted_array = np.argsort(array_a)
smallest_4_elements = sorted_array[:4]
largest_5_elements = sorted_array[-5:]

# Part (b)
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array_b[array_b == array_b.astype(int)]
float_elements = array_b[array_b != array_b.astype(int)]


print("Sorted Array:", sorted_array)
print("Indices of Sorted Array:", indices_sorted_array)
print("4 Smallest Elements:", smallest_4_elements)
print("5 Largest Elements:", largest_5_elements)

print("Integer Elements:", int_elements)
print("Float Elements:", float_elements)


Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]
Integer Elements: [1. 2. 3. 2.]
Float Elements: [1.2 2.2]


Q.3 You are given a weekly sales dataset and need to perform various operations
using NumPy broadcasting.
a) Generate your unique sales dataset:
 Take the sum of the ASCII values of the initials of your first and last
name. Call this value X. (If your initials are A B → ASCII sum = 65
+ 66 = 131 → sales = [131, 181, 231, 281, 331].)
 Create a NumPy array sales with values [X, X+50, X+100, X+150,
X+200].

b) Compute your personalized tax rate as ((X % 5) + 5) / 100.
 Use broadcasting to apply this tax rate to each sales value.
c) Adjust sales based on discount:
 If sales < X+100, apply a 5% discount.
 If sales >= X+100, apply a 10% discount.
d) Expand sales data for multiple weeks:
 Create a 3×5 matrix representing three weeks of sales by stacking
sales three times using broadcasting.
 Increase sales by 2% per week using element-wise broadcasting.

In [10]:
import numpy as np

# Part a
initials = input("Please enter your initials (2 letters): ")

if len(initials) == 2 and initials.isalpha():
    X = sum(ord(char) for char in initials)
    print(f"The sum of the ASCII values of your initials '{initials}' is: {X}")
else:
    print("Invalid input. Please enter exactly 2 alphabetic letters.")

sales = np.array([X, X + 50, X + 100, X + 150, X + 200])
print("Sales array:", sales)

# Part b
tax_rate = ((X % 5) + 5) / 100
print("Tax rate:", tax_rate)
sales_with_tax = sales * (1 + tax_rate)
print("Sales with tax applied:", sales_with_tax)

# Part c
discounted_sales = np.copy(sales).astype(np.float64)

# Apply a 5% discount for sales less than 259, 10% discount for sales >= 259
discounted_sales[sales < (X + 100)] *= 0.95
discounted_sales[sales >= (X + 100)] *= 0.90
print("Discounted sales:", discounted_sales)

# Part d
sales_matrix = np.tile(sales, (3, 1))
print("Sales matrix (3 weeks):")
print(sales_matrix)

# Apply 2% weekly increase to the sales matrix
sales_matrix = sales_matrix * (1 + 0.02)**np.arange(3)[:, np.newaxis]
print("Sales matrix with 2% weekly increase:")
print(sales_matrix)




Please enter your initials (2 letters): TK
The sum of the ASCII values of your initials 'TK' is: 159
Sales array: [159 209 259 309 359]
Tax rate: 0.09
Sales with tax applied: [173.31 227.81 282.31 336.81 391.31]
Discounted sales: [151.05 198.55 233.1  278.1  323.1 ]
Sales matrix (3 weeks):
[[159 209 259 309 359]
 [159 209 259 309 359]
 [159 209 259 309 359]]
Sales matrix with 2% weekly increase:
[[159.     209.     259.     309.     359.    ]
 [162.18   213.18   264.18   315.18   366.18  ]
 [165.4236 217.4436 269.4636 321.4836 373.5036]]


Q4. Generate x values using np.linspace() from -10 to 10 with 100 points. Use
each function from the list below and compute y values using NumPy:
 Y = x2
 Y = sin(x)
 Y = ex
 Y = log(|x| + 1)
Plot the chosen function using Matplotlib. Add title, labels, and grid for clarity.

In [14]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)

y1 = x**2
y2 = np.sin(x)
y3 = np.exp(x)
y4 = np.log(np.abs(x) + 1)

fig, axs = plt.subplots(2, 2, figsize=(10, 8))

# Plot y = x^2
axs[0, 0].plot(x, y1, label='y = x^2', color='b')
axs[0, 0].set_title('y = x^2')
axs[0, 0].set_xlabel('x')
axs[0, 0].set_ylabel('y')
axs[0, 0].grid(True)

# Plot y = sin(x)
axs[0, 1].plot(x, y2, label='y = sin(x)', color='r')
axs[0, 1].set_title('y = sin(x)')
axs[0, 1].set_xlabel('x')
axs[0, 1].set_ylabel('y')
axs[0, 1].grid(True)

# Plot y = e^x
axs[1, 0].plot(x, y3, label='y = e^x', color='g')
axs[1, 0].set_title('y = e^x')
axs[1, 0].set_xlabel('x')
axs[1, 0].set_ylabel('y')
axs[1, 0].grid(True)

# Plot y = log(|x| + 1)
axs[1, 1].plot(x, y4, label='y = log(|x| + 1)', color='purple')
axs[1, 1].set_title('y = log(|x| + 1)')
axs[1, 1].set_xlabel('x')
axs[1, 1].set_ylabel('y')
axs[1, 1].grid(True)

plt.tight_layout()
plt.show()
